/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as MapRouteImport } from './routes/map'
import { Route as ApiRouteRouteImport } from './routes/api/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as ApiReferenceDataRouteImport } from './routes/api/reference-data'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiShareIdRouteImport } from './routes/api/share.$id'
import { Route as ApiCourseCodeRouteImport } from './routes/api/course.$code'
import { Route as ApiAdminScrapeRouteImport } from './routes/api/admin.scrape'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteRoute = ApiRouteRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiReferenceDataRoute = ApiReferenceDataRouteImport.update({
  id: '/reference-data',
  path: '/reference-data',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiShareIdRoute = ApiShareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiShareRoute,
} as any)
const ApiCourseCodeRoute = ApiCourseCodeRouteImport.update({
  id: '/course/$code',
  path: '/course/$code',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiAdminScrapeRoute = ApiAdminScrapeRouteImport.update({
  id: '/admin/scrape',
  path: '/admin/scrape',
  getParentRoute: () => ApiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/map': typeof MapRoute
  '/timetable': typeof TimetableRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reference-data': typeof ApiReferenceDataRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/api/admin/scrape': typeof ApiAdminScrapeRoute
  '/api/course/$code': typeof ApiCourseCodeRoute
  '/api/share/$id': typeof ApiShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/map': typeof MapRoute
  '/timetable': typeof TimetableRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reference-data': typeof ApiReferenceDataRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/api/admin/scrape': typeof ApiAdminScrapeRoute
  '/api/course/$code': typeof ApiCourseCodeRoute
  '/api/share/$id': typeof ApiShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/map': typeof MapRoute
  '/timetable': typeof TimetableRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/reference-data': typeof ApiReferenceDataRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/api/admin/scrape': typeof ApiAdminScrapeRoute
  '/api/course/$code': typeof ApiCourseCodeRoute
  '/api/share/$id': typeof ApiShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/map'
    | '/timetable'
    | '/api/catalog'
    | '/api/health'
    | '/api/reference-data'
    | '/api/share'
    | '/p/$id'
    | '/api/admin/scrape'
    | '/api/course/$code'
    | '/api/share/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/map'
    | '/timetable'
    | '/api/catalog'
    | '/api/health'
    | '/api/reference-data'
    | '/api/share'
    | '/p/$id'
    | '/api/admin/scrape'
    | '/api/course/$code'
    | '/api/share/$id'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/map'
    | '/timetable'
    | '/api/catalog'
    | '/api/health'
    | '/api/reference-data'
    | '/api/share'
    | '/p/$id'
    | '/api/admin/scrape'
    | '/api/course/$code'
    | '/api/share/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRouteRoute: typeof ApiRouteRouteWithChildren
  MapRoute: typeof MapRoute
  TimetableRoute: typeof TimetableRoute
  PIdRoute: typeof PIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/reference-data': {
      id: '/api/reference-data'
      path: '/reference-data'
      fullPath: '/api/reference-data'
      preLoaderRoute: typeof ApiReferenceDataRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/share/$id': {
      id: '/api/share/$id'
      path: '/$id'
      fullPath: '/api/share/$id'
      preLoaderRoute: typeof ApiShareIdRouteImport
      parentRoute: typeof ApiShareRoute
    }
    '/api/course/$code': {
      id: '/api/course/$code'
      path: '/course/$code'
      fullPath: '/api/course/$code'
      preLoaderRoute: typeof ApiCourseCodeRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/admin/scrape': {
      id: '/api/admin/scrape'
      path: '/admin/scrape'
      fullPath: '/api/admin/scrape'
      preLoaderRoute: typeof ApiAdminScrapeRouteImport
      parentRoute: typeof ApiRouteRoute
    }
  }
}

interface ApiShareRouteChildren {
  ApiShareIdRoute: typeof ApiShareIdRoute
}

const ApiShareRouteChildren: ApiShareRouteChildren = {
  ApiShareIdRoute: ApiShareIdRoute,
}

const ApiShareRouteWithChildren = ApiShareRoute._addFileChildren(
  ApiShareRouteChildren,
)

interface ApiRouteRouteChildren {
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReferenceDataRoute: typeof ApiReferenceDataRoute
  ApiShareRoute: typeof ApiShareRouteWithChildren
  ApiAdminScrapeRoute: typeof ApiAdminScrapeRoute
  ApiCourseCodeRoute: typeof ApiCourseCodeRoute
}

const ApiRouteRouteChildren: ApiRouteRouteChildren = {
  ApiCatalogRoute: ApiCatalogRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReferenceDataRoute: ApiReferenceDataRoute,
  ApiShareRoute: ApiShareRouteWithChildren,
  ApiAdminScrapeRoute: ApiAdminScrapeRoute,
  ApiCourseCodeRoute: ApiCourseCodeRoute,
}

const ApiRouteRouteWithChildren = ApiRouteRoute._addFileChildren(
  ApiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRouteRoute: ApiRouteRouteWithChildren,
  MapRoute: MapRoute,
  TimetableRoute: TimetableRoute,
  PIdRoute: PIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
