/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiWalkRouteRouteImport } from './routes/api/walk-route'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as ApiReferenceDataRouteImport } from './routes/api/reference-data'
import { Route as ApiProfRatingRouteImport } from './routes/api/prof-rating'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiShareIdRouteImport } from './routes/api/share.$id'
import { Route as ApiCourseCodeRouteImport } from './routes/api/course.$code'
import { Route as ApiAdminScrapeRouteImport } from './routes/api/admin.scrape'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalkRouteRoute = ApiWalkRouteRouteImport.update({
  id: '/api/walk-route',
  path: '/api/walk-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceDataRoute = ApiReferenceDataRouteImport.update({
  id: '/api/reference-data',
  path: '/api/reference-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfRatingRoute = ApiProfRatingRouteImport.update({
  id: '/api/prof-rating',
  path: '/api/prof-rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareIdRoute = ApiShareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiShareRoute,
} as any)
const ApiCourseCodeRoute = ApiCourseCodeRouteImport.update({
  id: '/api/course/$code',
  path: '/api/course/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScrapeRoute = ApiAdminScrapeRouteImport.update({
  id: '/api/admin/scrape',
  path: '/api/admin/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/timetable': typeof TimetableRoute
  '/tree': typeof TreeRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/prof-rating': typeof ApiProfRatingRoute
  '/api/reference-data': typeof ApiReferenceDataRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/api/walk-route': typeof ApiWalkRouteRoute
  '/p/$id': typeof PIdRoute
  '/api/admin/scrape': typeof ApiAdminScrapeRoute
  '/api/course/$code': typeof ApiCourseCodeRoute
  '/api/share/$id': typeof ApiShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/timetable': typeof TimetableRoute
  '/tree': typeof TreeRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/prof-rating': typeof ApiProfRatingRoute
  '/api/reference-data': typeof ApiReferenceDataRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/api/walk-route': typeof ApiWalkRouteRoute
  '/p/$id': typeof PIdRoute
  '/api/admin/scrape': typeof ApiAdminScrapeRoute
  '/api/course/$code': typeof ApiCourseCodeRoute
  '/api/share/$id': typeof ApiShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/timetable': typeof TimetableRoute
  '/tree': typeof TreeRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/prof-rating': typeof ApiProfRatingRoute
  '/api/reference-data': typeof ApiReferenceDataRoute
  '/api/share': typeof ApiShareRouteWithChildren
  '/api/walk-route': typeof ApiWalkRouteRoute
  '/p/$id': typeof PIdRoute
  '/api/admin/scrape': typeof ApiAdminScrapeRoute
  '/api/course/$code': typeof ApiCourseCodeRoute
  '/api/share/$id': typeof ApiShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/timetable'
    | '/tree'
    | '/api/catalog'
    | '/api/health'
    | '/api/prof-rating'
    | '/api/reference-data'
    | '/api/share'
    | '/api/walk-route'
    | '/p/$id'
    | '/api/admin/scrape'
    | '/api/course/$code'
    | '/api/share/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/timetable'
    | '/tree'
    | '/api/catalog'
    | '/api/health'
    | '/api/prof-rating'
    | '/api/reference-data'
    | '/api/share'
    | '/api/walk-route'
    | '/p/$id'
    | '/api/admin/scrape'
    | '/api/course/$code'
    | '/api/share/$id'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/timetable'
    | '/tree'
    | '/api/catalog'
    | '/api/health'
    | '/api/prof-rating'
    | '/api/reference-data'
    | '/api/share'
    | '/api/walk-route'
    | '/p/$id'
    | '/api/admin/scrape'
    | '/api/course/$code'
    | '/api/share/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  TimetableRoute: typeof TimetableRoute
  TreeRoute: typeof TreeRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfRatingRoute: typeof ApiProfRatingRoute
  ApiReferenceDataRoute: typeof ApiReferenceDataRoute
  ApiShareRoute: typeof ApiShareRouteWithChildren
  ApiWalkRouteRoute: typeof ApiWalkRouteRoute
  PIdRoute: typeof PIdRoute
  ApiAdminScrapeRoute: typeof ApiAdminScrapeRoute
  ApiCourseCodeRoute: typeof ApiCourseCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/walk-route': {
      id: '/api/walk-route'
      path: '/api/walk-route'
      fullPath: '/api/walk-route'
      preLoaderRoute: typeof ApiWalkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference-data': {
      id: '/api/reference-data'
      path: '/api/reference-data'
      fullPath: '/api/reference-data'
      preLoaderRoute: typeof ApiReferenceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prof-rating': {
      id: '/api/prof-rating'
      path: '/api/prof-rating'
      fullPath: '/api/prof-rating'
      preLoaderRoute: typeof ApiProfRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$id': {
      id: '/api/share/$id'
      path: '/$id'
      fullPath: '/api/share/$id'
      preLoaderRoute: typeof ApiShareIdRouteImport
      parentRoute: typeof ApiShareRoute
    }
    '/api/course/$code': {
      id: '/api/course/$code'
      path: '/api/course/$code'
      fullPath: '/api/course/$code'
      preLoaderRoute: typeof ApiCourseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scrape': {
      id: '/api/admin/scrape'
      path: '/api/admin/scrape'
      fullPath: '/api/admin/scrape'
      preLoaderRoute: typeof ApiAdminScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiShareRouteChildren {
  ApiShareIdRoute: typeof ApiShareIdRoute
}

const ApiShareRouteChildren: ApiShareRouteChildren = {
  ApiShareIdRoute: ApiShareIdRoute,
}

const ApiShareRouteWithChildren = ApiShareRoute._addFileChildren(
  ApiShareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  TimetableRoute: TimetableRoute,
  TreeRoute: TreeRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfRatingRoute: ApiProfRatingRoute,
  ApiReferenceDataRoute: ApiReferenceDataRoute,
  ApiShareRoute: ApiShareRouteWithChildren,
  ApiWalkRouteRoute: ApiWalkRouteRoute,
  PIdRoute: PIdRoute,
  ApiAdminScrapeRoute: ApiAdminScrapeRoute,
  ApiCourseCodeRoute: ApiCourseCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
